### ISSUE TITLE
CRUD 함수

### ISSUE THREAD

**Issue by HyeokyYun** [HyeokyYun/2020OSS_Lab13#3]

**Comment by HyeokyYun** [comment]
추가, 조회, 수정, 삭제, 저장, 검색(3개), 등수,... 등

**Comment by ParkSuah** [comment]
<기본>
추가
읽기
수정
삭제
파일저장
파일로드
<검색>
이름
평균
등수

**Comment by ParkSuah** [comment]
등수 검색 -> ex) 2를 입력하면 2등의 정보를 출력
등수 나열 -> 등수별로 데이터를 나열함
